### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './light_weight_refinenet/resnet50.pth.tar'

### ISSUE THREAD

**Issue by Marwanon** [choicelab/grasping-invisible#4]
Hi
I have tried to run the code using this command  
> python main.py

I got this error 
IOError: [Errno 2] No such file or directory: './light_weight_refinenet/resnet50.pth.tar'

I have check the path I did not get the resnet50.pth.tar

may you help  to fix this issue

**Comment by st2yang** [comment]
Did you try to download the weight files by running downloads.sh?
