### ISSUE TITLE
Which camera to use?

### ISSUE THREAD

**Issue by xukechun** [choicelab/grasping-invisible#5]
Hello, I'm really interested in this work. Recently we try to test the released model in real-world experiments. However, the robot always tends to grasp at the very beginning without executing pushing for de-clutter. I wonder if this is due to the fact the depth images are not accurate enough. So I want to ask which camera do you use?

**Comment by st2yang** [comment]
I used an RealSense D415. Did you manage to fix the issue?

**Comment by xukechun** [comment]
Yes. We have fixed the issue before. Thanks very much for the answer.
