### ISSUE TITLE
downloads.sh error

### ISSUE THREAD

**Issue by quyouyuan** [choicelab/grasping-invisible#7]
dell@dell-Precision-7920-Tower:~/桌面/grasping-invisible-master$ sh downloads.shDownloading model weights...
downloads.sh: 4: downloads.sh: curl: not found
awk: cannot open ./cookie (No such file or directory)
downloads.sh: 5: downloads.sh: curl: not found
rm: 无法删除'cookie': 没有那个文件或目录
unzip:  cannot find or open pre-trained.zip, pre-trained.zip.zip or pre-trained.zip.ZIP.
rm: 无法删除'pre-trained.zip': 没有那个文件或目录
mv: 无法获取'pre-trained/resnet50.pth.tar' 的文件状态(stat): 没有那个文件或目录
Done.

Hello! Why do I make the above errors when I download the pre trained model by running "sh downloads"? The prompt error is: unable to get the file status (STAT) of 'pre-trained / resnet50. PTH. Tar': there is no such file or directory。

**Comment by st2yang** [comment]
The error msg says curl is not found, which means you need to install it on windows or switch to linux. Or you can find the google drive link in the shell script.

**Comment by quyouyuan** [comment]
Thank you for your reply. I'm already downloads on Google google link !!
